### ISSUE TITLE
[Feature]: hcloud_server data source should return a list in case of with_selector

### ISSUE THREAD

**Issue by tenczardavid** [hetznercloud/terraform-provider-hcloud#420] opened 2021-07-31 18:48 UTC
### What whould you like to see?

I came across this limitation of the `hcloud_server` data source while I was trying to implement a workaround to solve the API limitations in the case of subnetworks.

My current module implementation:

```hcl
locals {
  sanitized_subnet_id    = replace(var.subnet_id, "/[^a-zA-Z0-9]+/", "-")
  sanitized_subnet_range = replace(var.subnet_range, "/[^a-zA-Z0-9]+/", "-")
}

data "hcloud_server" "self" {
  depends_on    = [hcloud_server.self]
  with_selector = "server_subnet_range==${local.sanitized_subnet_range}"
}

resource "hcloud_server" "self" {
  name         = var.name
  location     = var.location
  image        = var.image
  server_type  = var.type
  ssh_keys     = var.ssh_key_ids
  firewall_ids = var.firewall_ids
  labels = merge(
    var.labels,
    {
      server_subnet_id    = local.sanitized_subnet_id
      server_subnet_range = local.sanitized_subnet_range
    }
  )
}

resource "hcloud_server_network" "self" {
  server_id = hcloud_server.self.id
  subnet_id = var.subnet_id
  alias_ips = var.alias_ips
  ip        = cidrhost(var.subnet_range, length(data.hcloud_server.self.*.id))
}
```

As you can see I was trying to use labels to create the missing reference between a server and a subnetwork. In this implementation I wanted to use the data source `hcloud_server` to query all the servers created in a subnet, using label selectors. To my surprise, the data source fails as it can't handle lists as an output.

In my opinion, if we use the `with_selector` argument we should be able to get a list/map of servers as an output. If we don't want to introduce breaking changes then we could create a new data source `hcloud_servers` to cover this use-case, similarly how other providers did it.

**Comment by LKaemmerling** [comment] 2021-08-25 09:53
Hey @tenczardavid,

your request is basically a duplicate of: https://github.com/hetznercloud/terraform-provider-hcloud/issues/387. We plan to introduce new datasources that supports a list of servers.

**Closed as completed by LKaemmerling** 2021-08-25 09:53 UTC
Labels: duplicate, enhancement
