### ISSUE TITLE
[Bug]: ens10 missing

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/terraform-provider-hcloud#396] opened 2021-06-28 10:33 UTC
### What happened?

Same issue as https://github.com/hetznercloud/terraform-provider-hcloud/issues/161 but with hcloud_server type "cx11" and hcloud_network_subnet type "cloud". In ssh the server doesn't have `ens10` only `eth0` and `lo`.

### What did you expect to happen?

`ens10` should be there. In hcloud website it shows everything is correct. I tried recreating the servers a few times to see if it's a race condition but it's happening every time. I tried using hcloud_network_subnet with either network_id or subnet_id but it fails with both.

### Please provide a minimal working example

See https://github.com/hetznercloud/terraform-provider-hcloud/issues/161

**Comment by LKaemmerling** [comment] 2021-06-28 10:39
@rightaway can you please provide more details? Like which location, can you give me also the IDs of your server & network?

**Comment by rightaway** [comment] 2021-06-28 10:52
If you run this then log in with root and run `ip a` you won't see `ens10`.

```
resource "hcloud_network_subnet" "thesubnet" {
  ip_range = "10.0.0.32/29"
  network_id = "${hcloud_network.network.id}"
  network_zone = "eu-central"
  type = "cloud"
}

resource "hcloud_server" "servershome" {
  datacenter = "nbg1-dc3"
  name = "servershome"
  server_type = "cx11"
  image = "debian-10"
}

resource "hcloud_server_network" "servnet" {
  ip = "10.0.0.33"
  subnet_id = "${hcloud_network_subnet.thesubnet.id}"
  server_id = "${hcloud_server.servershome.id}"
}

resource "hcloud_network" "network" {
  ip_range = "10.0.0.0/24"
  name = "network"
}

terraform {
  required_providers {
    hcloud = {
      version = "~> 1.27.1"
      source = "hetznercloud/hcloud"
    }
  }
}
```

**Comment by LKaemmerling** [comment] 2021-06-28 11:11
Hey @rightaway,

i tried it just now and for me it works perfectly, can you try it again?

**Comment by rightaway** [comment] 2021-06-28 12:30
It must have been an intermittent problem. It was like this maybe for an hour on many servers. I've seen it before too but not recently. Do you sometimes get reports of this issue more recently or is it just me?

If it happens again is there a workaround? How can `ens10` be manually set when all the networking is correct in hcloud website but just does not appear in `ip` command?

**Comment by LKaemmerling** [comment] 2021-06-28 12:51
Hey @rightaway,

i talked with our Networks Team and it looked like there was a smaller issue that led to a missing attachment of the network device on the VM. Therefore there is nothing you (as a customer) can do in this case instead of writing a support ticket.

As the issue is solved, and not a terraform related issue I will close the issue here.

**Closed as completed by LKaemmerling** 2021-06-28 12:51 UTC
Labels: bug
