### ISSUE TITLE
Any plans on supporting the DNS API via Terraform? 

### ISSUE THREAD

**Issue by spommerening** [hetznercloud/terraform-provider-hcloud#274] opened 2020-11-27 14:26 UTC
I learnt about the DNS console which also provides an API. 

https://www.hetzner.com/de/dns-console

Do you have any plans on supporting this with Terraform?

**Comment by LKaemmerling** [comment] 2020-11-27 14:58
The DNS Console is out of scope of this Terraform Provider. This Terraform Provider is only for Hetzner Cloud Resources. There are already community contributed Terraform Provider for the DNS API. These are not directly supported from Hetzner.

https://github.com/timohirt/terraform-provider-hetznerdns

Duplicate of #183

**Closed as completed by LKaemmerling** 2020-11-27 14:58 UTC
