### ISSUE TITLE
[Bug]:  invalid rdns id after manually deleting a cloud server

### ISSUE THREAD

**Issue by schmidp** [hetznercloud/terraform-provider-hcloud#710] opened 2023-07-06 14:02 UTC
### What happened?

We are creating a server and adding an rdns:

```
resource "hcloud_rdns" "server" {
  server_id  = hcloud_server.server.id
  ip_address = hcloud_server.server.ipv4_address
  dns_ptr    = format("%s.%s", hcloud_server.server.name, var.base_domain)
}
```

When we manually delete the server in the hetzner console, terraform afterwards fails during the plan with:

```
│ Error: invalid rdns id s-34558311-162.55.48.8
│ 
│   with module.kube-or.module.control_planes[1].hcloud_rdns.server[0],
│   on kube-or/host/main.tf line 94, in resource "hcloud_rdns" "server":
│   94: resource "hcloud_rdns" "server" {
│ 
```

### What did you expect to happen?

The hcloud_rdns resource is not found and recreated.

### Please provide a minimal working example
```
resource "hcloud_server" "server" {
  name               = local.name
  image              = var.snapshot_id
  server_type        = var.server_type
  location           = var.location
  ssh_keys           = var.ssh_keys
  firewall_ids       = var.firewall_ids
  placement_group_id = var.placement_group_id
  backups            = var.backups
  user_data          = data.cloudinit_config.config.rendered

  network {
    network_id = var.network_id
    ip         = var.private_ipv4
  }
}

resource "hcloud_rdns" "server" {
  server_id  = hcloud_server.server.id
  ip_address = hcloud_server.server.ipv4_address
  dns_ptr    = format("%s.%s", hcloud_server.server.name, "example.com")
}
````

**Comment by apricote** [comment] 2023-07-13 11:50
Hey @schmidp,

I was able to reproduce your issue and found the cause. Will be fixed by #720.

**Closed as completed** 2023-07-13 12:11 UTC
Labels: bug
