### ISSUE TITLE
[Feature]: add primary private_ipv4_address datasource for hcloud_server

### ISSUE THREAD

**Issue by marcoatenway** [hetznercloud/terraform-provider-hcloud#557] opened 2022-08-15 07:37 UTC
### What whould you like to see?

**This is a copy of the closed ticket: #551 the ticket is not resolved. the mentioned object [...].network.ip does not exist**

the assigned private ip address should be exported as a datasource the same as the public IP address:

${hcloud_server.fancy-vm0.private_ipv4_address}

This is necessary to build highly dynamic infrastructure where you dont define any addresses because they are registered i.e. in DNS by terraform

**Comment by LKaemmerling** [comment] 2022-08-16 13:10
Hey @marcoatenway,

there is no need to create a new issue. 

Duplicate of #551 551

**Closed as completed by LKaemmerling** 2022-08-16 13:10 UTC
Labels: enhancement
