### ISSUE TITLE
crash when running terraform destroy

### ISSUE THREAD

**Issue by wolverian** [hetznercloud/terraform-provider-hcloud#323] opened 2021-02-26 13:24 UTC
[crash.log](https://github.com/hetznercloud/terraform-provider-hcloud/files/6049872/crash.log)

**Comment by LKaemmerling** [comment] 2021-06-22 05:08
Hey @wolverian,

i guess this was caused by a smaller API outage we had at around this time. I will close the issue here for now, if you again or still encounter the issue feel free to reopen this issue or create a new.

**Closed as completed by LKaemmerling** 2021-06-22 05:08 UTC
