### ISSUE TITLE
[Bug]: user_data does not allow executing shell script

### ISSUE THREAD

**Issue by rbjorklin** [hetznercloud/terraform-provider-hcloud#572] opened 2022-09-23 06:02 UTC
### What happened?

I see my script copied as desired into: `/var/lib/cloud/instances/*/scripts/part-001`

### What did you expect to happen?

I expected the script to get executed. As the [documentation suggest should be possible](https://cloudinit.readthedocs.io/en/latest/topics/format.html#user-data-script).

### Please provide a minimal working example

```hcl
resource "hcloud_server" "node" {
  count       = 1
  name        = "test"
  image       = "fedora-36"
  server_type = "cpx21"
  location    = "ash"
  ssh_keys    = "<your key here>"
  user_data   = <<EOT
  #!/bin/bash
  dnf install --assumeyes zsh
  EOT
}
```

**Comment by apricote** [comment] 2022-11-07 13:58
The issue is that with heredoc strings (`<<EOT`) the formatting whitespace infront of your script is copied too, which causes the script to fail during execution. You can see this for yourself by searching for `part-001` in the cloud-init logfile `/var/log/cloud-init.log`:

```
2022-11-07 13:51:37,431 - subp.py[DEBUG]: Exec format error. Missing #! in script?
Command: ['/var/lib/cloud/instance/scripts/part-001']
```

You can fix this by removing the spaces infront of your script:

```diff
 resource "hcloud_server" "node" {
   count       = 1
   name        = "test"
   image       = "fedora-36"
   server_type = "cpx21"
   location    = "ash"
   ssh_keys    = "<your key here>"
   user_data   = <<EOT
-  #!/bin/bash
-  dnf install --assumeyes zsh
+#!/bin/bash
+dnf install --assumeyes zsh
   EOT
 }
```

I am going to close this issue. Please feel free to reopen/comment here if you still have issues with your configuration and cloud-init.

**Closed as completed by apricote** 2022-11-07 13:58 UTC
Labels: bug
