### ISSUE TITLE
DNS resources missing

### ISSUE THREAD

**Issue by jeff1985** [hetznercloud/terraform-provider-hcloud#296] opened 2021-01-06 12:17 UTC
Hi,

I'm missing the possibility to manage hetzner DNS resources. Other major cloud providers like Azure, AWS, DO etc have a supported terraform provider for managing DNS, which is essential to create any modern cloud application. Can you tell me, why this is not in scope here?

**Comment by LKaemmerling** [comment] 2021-01-06 17:36
The DNS console is a dedicated product, like the Cloud is. You can read more about it in #183.

Duplicate of #183

**Closed as completed by LKaemmerling** 2021-01-06 17:36 UTC
