### ISSUE TITLE
[Bug]: hcloud_primary_ip with type ipv6 has incomplete attribute ip_address

### ISSUE THREAD

**Issue by blackkaven** [hetznercloud/terraform-provider-hcloud#619] opened 2023-02-02 21:06 UTC
### What happened?

After creating a primary IP of type `ipv6` I would expect that the attribute field `ip_address ` reports the whole IP address and not only the subnet.

### What did you expect to happen?

Referencing the `ip_address` should return the whole ip address.

### Please provide a minimal working example

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.36.2"
    }
  }
}

provider "hcloud" {
  token = <YOUR TOKEN HERE>
}

resource "hcloud_primary_ip" "test_ipv6" {
  name                 = "test_ip_ipv6"
  type                   = "ipv6"
  datacenter       = "fsn1-dc14"
  assignee_type = "server"
  auto_delete     = false
}

output "debug" {
  value = hcloud_primary_ip.test_ipv6.ip_address
}
```

**Comment by apricote** [comment] 2023-02-03 09:55
Closing this, as it is a duplicate of #600

**Closed as not planned by apricote** 2023-02-03 09:55 UTC
Labels: bug, duplicate
