### ISSUE TITLE
[Bug]: Removing firewall_ids section from resource description of server does NOT remove the firewall from the server

### ISSUE THREAD

**Issue by mkarg** [hetznercloud/terraform-provider-hcloud#1061] opened 2024-12-17 17:40 UTC
### What happened?

I have removed the section `firewall_ids` from `resource "hcloud_server"`, then executed `tofu plan` to see the resulting action. Strange but true, `tofu` told me that it won't change *anything*, while `hcloud firewall list` told me that the firewall *is* assigned to that hcloud server.

### What did you expect to happen?

I expected that `tofu plan` tells me it will remove the firewall from the hcloud server.

### Please provide a minimal working example

```main.tf
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.49.1"
    }
  }
}

variable "hetzner_token" {
  type = string
}

provider "hcloud" {
  token = var.hetzner_token
}

resource "hcloud_firewall" "f" {
  name = "f"

  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = [
      "0.0.0.0/0",
      "::/0"
    ]
  }
}

resource "hcloud_server" "s" {
  name         = "s"
  image        = "debian-12"
  server_type  = "cax11"
  datacenter   = "fsn1-dc14"
  firewall_ids = [
    hcloud_firewall.f.id
  ]
}
```

**Comment by jooola** [comment] 2024-12-20 11:07
Closing this ticket as it is a duplicate of https://github.com/hetznercloud/terraform-provider-hcloud/issues/998

**Closed as completed by jooola** 2024-12-20 11:07 UTC
Labels: bug
