### ISSUE TITLE
Allow to retrieve list of servers matching label expression

### ISSUE THREAD

**Issue by rkosegi** [hetznercloud/terraform-provider-hcloud#358] opened 2021-05-26 14:46 UTC
Currently it is possible to fetch only single server resource using `data "hcloud_server"`.
When multiple servers matching, error such as this is returned:

```
╷
│ Error: more than one Server found for selector "key=value"
│ 
│   on main.tf line 1, in data "hcloud_server" "all_servers":
│    1: data "hcloud_server" "all_servers" {
│ 
╵
```

It would be really nice to have possibility to retrieve all of them in form of list, so that I can perform bulk operation on matching entries.

**Comment by LKaemmerling** [comment] 2021-06-19 17:45
Duplicate of https://github.com/hetznercloud/terraform-provider-hcloud/issues/313

**Closed as completed by LKaemmerling** 2021-06-19 17:45 UTC
