### ISSUE TITLE
[Bug]: Sometimes attach server to network: cannot perform operation because server is locked (locked)

### ISSUE THREAD

**Issue by svenstaro** [hetznercloud/terraform-provider-hcloud#492] opened 2021-12-16 14:57 UTC
### What happened?

Sometimes I get
```
module.dynamic_environments["test"].hcloud_server_network.database: Destroying... [id=1337-1337]
module.dynamic_environments["test"].hcloud_volume_attachment.database: Destroying... [id=1337]
module.dynamic_environments["test"].hcloud_volume_attachment.database: Destruction complete after 3s
module.dynamic_environments["test"].hcloud_server_network.database: Destruction complete after 7s
module.dynamic_environments["test"].hcloud_server.database: Destroying... [id=1337]
module.dynamic_environments["test"].hcloud_server.database: Destruction complete after 2s
module.dynamic_environments["test"].hcloud_volume.database: Destroying... [id=1337]
module.dynamic_environments["test"].hcloud_volume.database: Destruction complete after 1s
module.dynamic_environments["test"].hcloud_volume.database: Creating...
module.dynamic_environments["test"].hcloud_volume.database: Creation complete after 6s [id=1337]
module.dynamic_environments["test"].hcloud_server.database: Creating...
module.dynamic_environments["test"].hcloud_server.database: Still creating... [10s elapsed]
module.dynamic_environments["test"].hcloud_server.database: Still creating... [20s elapsed]
module.dynamic_environments["test"].hcloud_server.database: Creation complete after 22s [id=1337]
module.dynamic_environments["test"].hcloud_server_network.database: Creating...
module.dynamic_environments["test"].hcloud_volume_attachment.database: Creating...
module.dynamic_environments["test"].hcloud_volume_attachment.database: Still creating... [10s elapsed]
module.dynamic_environments["test"].hcloud_server_network.database: Still creating... [10s elapsed]
module.dynamic_environments["test"].hcloud_volume_attachment.database: Still creating... [20s elapsed]
module.dynamic_environments["test"].hcloud_volume_attachment.database: Creation complete after 23s [id=1337]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵
╷
│ Error: attach server to network: cannot perform operation because server is locked (locked)
│ 
│   with module.dynamic_environments["test"].hcloud_server_network.database,
│   on deployment/main.tf line 60, in resource "hcloud_server_network" "database":
│   60: resource "hcloud_server_network" "database" {
│ 
╵
Releasing state lock. This may take a few moments...


```

This appears to happen randomly but can be reliably triggered when repeatedly destroying and recreating resources. I suspect a race condition such as in #286.

### What did you expect to happen?

It should run without errors every time.

### Please provide a minimal working example

```hcl
resource "hcloud_server" "database" {
  name        = "test-database"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  location    = "fsn1"
  ssh_keys    = [var.ssh_key_name]
  user_data = templatefile("${path.root}/config/database_cloud_init", {
    test = "lol"
  })
  labels = {
    purpose = "database"
  }
}

resource "hcloud_server_network" "database" {
  server_id = hcloud_server.database.id
  subnet_id = hcloud_network_subnet.deployment.id
}

resource "hcloud_volume" "database" {
  name      = "test-database"
  size      = 50
  location  = "fsn1"
  automount = false
  format    = "ext4"
  labels = {
    purpose = "database"
  }
}

resource "hcloud_volume_attachment" "database" {
  volume_id = hcloud_volume.database.id
  server_id = hcloud_server.database.id
}
```

I suggest a script such as
```sh
while true; do
  terraform taint hcloud_volume_attachment.database
  terraform taint hcloud_volume.database
  terraform taint hcloud_server_network.database
  terraform taint hcloud_server.database
  terraform apply -auto-approve
done
```

This will likely trigger the problem at some point.

**Comment by fhofherr** [comment] 2022-01-03 11:22
Hi @svenstaro,

does the issue still occur? I tried your minimal working example quite a few times this morning and was not able to reproduce it. Additionally I noticed your network config was missing from the example.

```
terraform {
  required_providers {
    hcloud = {
      source     = "hetznercloud/hcloud"
      version    = "1.32.2"
    }
  }
}

resource "hcloud_network" "deployment" {
    name     = "deployment"
    ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "deployment" {
    network_id   = hcloud_network.deployment.id
    type         = "cloud"
    network_zone = "eu-central"
    ip_range     = "10.1.0.0/16"
}

resource "hcloud_server" "database" {
  name        = "test-database"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  location    = "fsn1"
  ssh_keys    = ["REDACTED"]
  # user_data = templatefile("${path.root}/config/database_cloud_init", {
  #   test = "lol"
  # })
  labels = {
    purpose = "database"
  }
}


resource "hcloud_server_network" "database" {
  server_id = hcloud_server.database.id
  subnet_id = hcloud_network_subnet.deployment.id
}

resource "hcloud_volume" "database" {
  name      = "test-database"
  size      = 50
  location  = "fsn1"
  automount = false
  format    = "ext4"
  labels = {
    purpose = "database"
  }
}

resource "hcloud_volume_attachment" "database" {
  volume_id = hcloud_volume.database.id
  server_id = hcloud_server.database.id
}
```

**Comment by svenstaro** [comment] 2022-01-03 12:13
We currently have no problems with this but it definitely was a problem for some time. We didn't change anything from our side so for all we know it's a Hetzner issue. However, I'm not sure we can just assume this problem to be fixed from Hetzner forever so it might still be good to add something here from the provider's side.

**Comment by LKaemmerling** [comment] 2022-02-14 11:36
Hey, i will close the issue as it seems that the error is fixed. If the problem is still there, feel free to reopen the issue or create a new.

**Closed as completed by LKaemmerling** 2022-02-14 11:36 UTC
Labels: bug
