### ISSUE TITLE
PLUGIN CRASH AT DELETING INFRA

### ISSUE THREAD

**Issue by chriskosch** [hetznercloud/terraform-provider-hcloud#580] opened 2022-10-24 11:42 UTC
hcloud_server_network.srv_network[0]: Still destroying... [id=24966132-2141912, 10s elapsed]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may    
│ contain more details.
╵

Stack trace from the terraform-provider-hcloud_v1.35.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1307bf7]

goroutine 109 [running]:
github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress.func1()
        github.com/hetznercloud/hcloud-go@v1.35.2/hcloud/action.go:196 +0x1b7
created by github.com/hetznercloud/hcloud-go/hcloud.(*ActionClient).WatchOverallProgress
        github.com/hetznercloud/hcloud-go@v1.35.2/hcloud/action.go:189 +0x12e

Error: The terraform-provider-hcloud_v1.35.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by apricote** [comment] 2022-11-07 13:21
Hi @chriskosch,

can you reproduce this issue? If yes, it would be great if you could provide us with a list of steps and a minimally working example.

**Comment by apricote** [comment] 2022-11-23 10:36
Hi @chriskosch, I am going to close this issue as it is a duplicate of #491. Please use that ticket for any further comments.

If you still have the issue, it would be great if you can send me debug logs, I describe the process for that here: https://github.com/hetznercloud/terraform-provider-hcloud/issues/491#issuecomment-1324848120

**Closed as not planned by apricote** 2022-11-23 10:36 UTC
Labels: bug, duplicate, crash

**Comment by chriskosch** [comment] 2022-11-23 10:37
Thank you
