### ISSUE TITLE
[Bug]: Cannot remove subnet because servers are attached to it.

### ISSUE THREAD

**Issue by huckleberrie** [hetznercloud/terraform-provider-hcloud#412] opened 2021-07-22 10:03 UTC
### What happened?

While executing a `terraform destroy` our `subnet` resource wont be destroyed properly. 

`Error: cannot remove subnet because servers are attached to it (service_error)`

We are using version `1.27.2`.

I also read about a similar issue that was resolved by adding dependencies to each `server` for the `network` and the `subnet`. Unfortunately this does not seem to fix the problem for us.

### What did you expect to happen?

We expected to see the `subnet` being destroyed together with the `network` so that we are left with a clean project.

### Please provide a minimal working example

```
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.27.2"
    }
  }
}

resource "hcloud_network" "network" {
  name     = "internal-network"
  ip_range = "10.11.0.0/20"
}

resource "hcloud_network_subnet" "network-subnet" {
  type         = "cloud"
  network_id   = hcloud_network.network.id
  network_zone = "eu-central"
  ip_range     = "10.11.0.0/24"
}

resource "hcloud_firewall" "firewall-ssh-allowed" {
  name = "firewall-ssh-allowed"
  rule {
    direction = "in"
    protocol  = "tcp"
    port      = "22"
    source_ips = [
      "0.0.0.0/0",
      "::/0"
   ]
  }
  rule {
    direction = "in"
    protocol  = "icmp"
    source_ips = [
      "0.0.0.0/0",
      "::/0"
   ]
  }
}

resource "hcloud_firewall" "firewall-master-worker-block-everything-external" {
  name = "firewall-master-worker-block-everything-external"
}

resource "hcloud_server" "ct_server" {

  name           = "${var.cluster_prefix}-ct-${var.cluster_id}"
  server_type    = var.ct_server_type
  image          = var.image_vm
  location       = var.location

  network {
    network_id   = hcloud_network.network.id
  }

  firewall_ids   = [hcloud_firewall.firewall-ssh-allowed.id]

  depends_on = [
    hcloud_network.network,
    hcloud_network_subnet.network-subnet
  ]
}
```

**Comment by LKaemmerling** [comment] 2021-07-26 08:06
Duplicate of #388

**Closed as completed by LKaemmerling** 2021-07-26 08:06 UTC
Labels: bug
