### ISSUE TITLE
[Bug]: Can't change server architecture

### ISSUE THREAD

**Issue by nomorepanic** [hetznercloud/terraform-provider-hcloud#1000] opened 2024-09-15 20:07 UTC
### What happened?

If I try to change the server architecture, say from CX to CA an error occurs.

### What did you expect to happen?

I'd expect the provider to destroy and recreate the server, as it happens with Terraform providers for other cloud platforms.

### Please provide a minimal working example

```diff
resource "hcloud_server" "myserver" {
-  server_type  = "cx22"
+  server_type  = "cax11"
}
```

**Comment by jooola** [comment] 2024-10-14 08:34
Closing as duplicate of https://github.com/hetznercloud/terraform-provider-hcloud/issues/853

**Closed as completed by jooola** 2024-10-14 08:34 UTC
Labels: bug
