### ISSUE TITLE
terraform 0.14.4 - init never ends...

### ISSUE THREAD

**Issue by lachnerd** [hetznercloud/terraform-provider-hcloud#300] opened 2021-01-11 16:30 UTC
If i want to import hcloud provider with 'terraform init' - it never returns from

> Installing hetznercloud/hcloud v1.23.0...

`terraform {
  required_providers {    
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "= 1.23.0"
    }
  }
}`

Running with terraform 0.14.4

**Comment by the-antz** [comment] 2021-01-11 19:10
Same here with terraform 0.13.5.

**Comment by LKaemmerling** [comment] 2021-01-11 19:30
Are you a Telekom customer? The download/installation is not part of the provider. This is done by terraform directly, basically it downloads the binaries from GitHub (As of TF 0.13). Github hosts the assets at AWS S3. The peering between AWS and the German Telekom is overloaded/ to small since a few weeks which affects all downloads from GitHub. I don't see any other possible problem and even if there would be another problem, it wouldn't be something we could fix, as our provider is only called when it is already installed. Based on your logs it looks like the problem is already at the download/installation which is controlled by terraform itself.

**Comment by the-antz** [comment] 2021-01-11 19:46
I use 1&1 but they seem to have the same horrible peering to AWS. A week or two ago I got a download speed in the range of bytes/s when downloading from github.
Are the `hashicorp/*` modules hosted somewhere else? Because I can download these without issues.

**Comment by LKaemmerling** [comment] 2021-01-11 19:57
I don’t know, maybe they are distributed through another way (maybe through a CDN).

**Comment by LKaemmerling** [comment] 2021-01-12 06:26
I will close the issue here now, as this is not in our responsibility. If you still encounter this issue, please talk to your ISP (check the peering with Github/AWS) or write to the terraform guys.

**Closed as completed by LKaemmerling** 2021-01-12 06:26 UTC

**Comment by lachnerd** [comment] 2021-01-12 10:11
> Are you a Telekom customer? The download/installation is not part of the provider. This is done by terraform directly, basically it downloads the binaries from GitHub (As of TF 0.13). Github hosts the assets at AWS S3. The peering between AWS and the German Telekom is overloaded/ to small since a few weeks which affects all downloads from GitHub. I don't see any other possible problem and even if there would be another problem, it wouldn't be something we could fix, as our provider is only called when it is already installed. Based on your logs it looks like the problem is already at the download/installation which is controlled by terraform itself.

I understand this is not a hcloud problem but do have any workaround for this problem ?

**Comment by LKaemmerling** [comment] 2021-01-12 10:14
@lachnerd, nope there is basically no workaround one idea would be using a VPN to download it.
