### ISSUE TITLE
[Bug]: Stuck at removing firewall rule before updating servers not to use it

### ISSUE THREAD

**Issue by ion1** [hetznercloud/terraform-provider-hcloud#454] opened 2021-08-30 16:51 UTC
### What happened?

I added a `hcloud_firewall` resource, changed `hcloud_server` resources to refer to that and removed the old `hcloud_firewall` resource. `terraform apply` created the new firewall but appears to be stuck attempting to remove the old one before even trying to replace the servers' references to it.

The terraform plan includes:

```
  # hcloud_firewall.general will be destroyed
  - resource "hcloud_firewall" "general" {
      - id     = "118248" -> null
      - labels = {} -> null
      - name   = "General" -> null

      - rule {
          - description     = "ICMP" -> null
          - destination_ips = [] -> null
          - direction       = "in" -> null
          - protocol        = "icmp" -> null
          - source_ips      = [
              - "0.0.0.0/0",
              - "::/0",
            ] -> null
        }
    }

  # hcloud_firewall.control_plane will be created
  + resource "hcloud_firewall" "control_plane" {
      + id   = (known after apply)
      + name = "Control Plane"

      + rule {
          + description     = "ICMP"
          + destination_ips = []
          + direction       = "in"
          + protocol        = "icmp"
          + source_ips      = [
              + "0.0.0.0/0",
              + "::/0",
            ]
        }
    }

  # module.talos_master[0].hcloud_server.talos_machine will be updated in-place
  ~ resource "hcloud_server" "talos_machine" {
      ~ firewall_ids = [
          - 129482,
        ] -> (known after apply)
        id                 = "14081379"
        name               = "master-1"
        # (13 unchanged attributes hidden)
    }
```

The output from `terraform apply`:
```
hcloud_firewall.general: Destroying... [id=118248]
hcloud_firewall.control_plane: Creating...
hcloud_firewall.control_plane: Creation complete after 0s [id=132019]
hcloud_firewall.general: Still destroying... [id=118248, 10s elapsed]
hcloud_firewall.general: Still destroying... [id=118248, 20s elapsed]
hcloud_firewall.general: Still destroying... [id=118248, 30s elapsed]
hcloud_firewall.general: Still destroying... [id=118248, 40s elapsed]
╷
│ Error: firewall with ID 118248 is still in use (resource_in_use)
│
```

By running `terraform apply` with `-target` I got a plan which bypassed the removal of the old firewall and updated the servers successfully:

```
  # module.talos_master[0].hcloud_server.talos_machine will be updated in-place
  ~ resource "hcloud_server" "talos_machine" {
      ~ firewall_ids       = [
          - 118248,
          + 132019,
        ]
        id                 = "14081379"
        name               = "master-1"
        # (13 unchanged attributes hidden)
    }
```

```
module.talos_master[0].hcloud_server.talos_machine: Modifying... [id=14081379]
module.talos_master[0].hcloud_server.talos_machine: Modifications complete after 5s [id=14081379]
╷
│ Warning: Applied changes may be incomplete
│
```

After that, a plain `terraform apply` removed the old firewall successfully:

```
hcloud_firewall.general: Destroying... [id=118248]
hcloud_firewall.general: Destruction complete after 0s
```

### What did you expect to happen?

I expected the new firewall to be created, the servers to be updated to use that one, and the old firewall to be removed afterwards.

### Please provide a minimal working example

I'm afraid I'm currently at the server limit for my account and not in a position to remove existing servers to test this separately, but I believe this should replicate what I did:

First define a firewall and a server:

```terraform
terraform {
  required_version = "~> 1.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.30"
    }
  }
}

provider "hcloud" {
  token = ...
}

resource "hcloud_firewall" "test1" {
  name = "Test 1"

  rule {
    description = "ICMP"
    direction   = "in"
    protocol    = "icmp"
    source_ips  = ["0.0.0.0/0", "::/0"]
  }
}

resource "hcloud_server" "test" {
  name         = "test"
  server_type  = "cx11"
  location     = "hel1"
  firewall_ids = [hcloud_firewall.test1.id]
  image        = "ubuntu-20.04"
}
```

Run `terraform apply`.

Change:
```diff
-resource "hcloud_firewall" "test1" {
-  name = "Test 1"
+resource "hcloud_firewall" "test2" {
+  name = "Test 2"
```
and:
```diff
-  firewall_ids = [hcloud_firewall.test1.id]
+  firewall_ids = [hcloud_firewall.test2.id]
```

Run `terraform apply`.

**Comment by apricote** [comment] 2022-11-22 12:52
I think this was fixed by #464 (released in v1.32.0). I am unable to reproduce the issue with the latest provider version.

I am going to close the issue, please feel free to reopen it or create a new one if your problem still exists or you have any further questions.

**Closed as completed by apricote** 2022-11-22 12:52 UTC
Labels: bug
