### ISSUE TITLE
Flag provided but not defined: -var

### ISSUE THREAD

**Issue by kiwinesian** [hetznercloud/terraform-provider-hcloud#402] opened 2021-07-01 04:14 UTC
### What happened?

Returned error

```
{"changed": false, "msg": "Failed to validate Terraform configuration files: Error: Failed to parse command-line flags flag provided but not defined: -var Error: Too many command line arguments│  Expected at most one positional argument ╵For more help on using this command, run: terraform validate -help"}
```

### What did you expect to happen?

Server should be build.
The exact same configuration is running on an older server: older version of Terraform + the module.

Not sure if this is an Ansible issue too? :( 

But working on 1 server - copied the exact same file.

### Please provide a minimal working example

terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.27.2"
    }
  }
}

provider "hcloud" {
  token   = "${var.hcloud_token}"
}

# Private Network and subnets
resource "hcloud_network" "k8s-dev" {
  name     = "kubernetes-dev"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "master" {
  network_id   = "${hcloud_network.k8s-dev.id}"
  type         = "server"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}

resource "hcloud_network_subnet" "worker" {
  network_id   = "${hcloud_network.k8s-dev.id}"
  type         = "server"
  network_zone = "eu-central"
  ip_range     = "10.0.2.0/24"
}

resource "hcloud_server" "master" {
  count       = "${var.master_count}"
  name        = "ubu18-k8s-dev-01-master-${count.index}"
  image       = "ubuntu-18.04"
  server_type = "${var.master_servertype}"
  location    = "${var.datacenter}"
  user_data   = "${file("./user-data/cloud-config.yaml")}"
}

resource "hcloud_server_network" "master_network" {
  count      = "${length(hcloud_server.master)}"
  network_id = "${hcloud_network.k8s-dev.id}"
  server_id  = "${hcloud_server.master.*.id[count.index]}"
  ip         = "10.0.1.${count.index + 2}"
}

# Worker
resource "hcloud_server" "worker" {
  count       = "${var.worker_count}"
  name        = "ubu18-k8s-dev-01-worker-${count.index}"
  image       = "ubuntu-18.04"
  server_type = "${var.worker_servertype}"
  location    = "${var.datacenter}"
  user_data   = "${file("./user-data/cloud-config.yaml")}"
}

resource "hcloud_server_network" "worker_network" {
  count      = "${length(hcloud_server.worker)}"
  network_id = "${hcloud_network.k8s-dev.id}"
  server_id  = "${hcloud_server.worker.*.id[count.index]}"
  ip         = "10.0.2.${count.index + 1}"
}

resource "hcloud_floating_ip" "lbipv4" {
  count         = "${var.floatip_count}"
  type          = "ipv4"
  home_location = "${var.datacenter}"
}

**Comment by LKaemmerling** [comment] 2021-07-02 06:33
Hey @kiwinesian,

which terraform version do you use? It looks like your terraform configuration is not the right for the used version. This is not a bug in our provider, therefore I would like to close it here. Feel free to write under the issue, I will look how I can help you :)

**Closed as completed by LKaemmerling** 2021-07-02 06:33 UTC
Labels: bug

**Comment by kiwinesian** [comment] 2021-07-02 06:36
Hi @LKaemmerling 

thanks for attending this!
It was the Ansible that was not install properly - had to rebuilt everything using `pip` instead of getting it from `apt-get`.

Thank you so much!
