### ISSUE TITLE
Destroy cannot remove subnet

### ISSUE THREAD

**Issue by kgusarov** [hetznercloud/terraform-provider-hcloud#343] opened 2021-04-15 18:08 UTC
While performing terraform destroy in 9 out of 10 cases I end up with:

Error: cannot remove subnet because servers are attached to it (service_error)

Network resources:
```
resource "hcloud_network" "default_net" {
  ip_range        = local.default_net_range
  name            = "default"
}

resource "hcloud_network_subnet" "default_subnet" {
  ip_range        = local.default_subnet_range
  network_id      = hcloud_network.default_net.id
  network_zone    = "eu-central"
  type            = "cloud"
}
```

IPs and ranges:
```
locals {
  ...
  web_server_ip           = "172.16.0.4"
  default_net_range       = "172.16.0.0/12"
  default_subnet_range    = "172.16.0.0/16"
}
```

One of the provisioned servers:
```
resource "hcloud_server" "web_server" {
  image                 = "ubuntu-20.04"
  name                  = "web"
  server_type           = "cx21"
  datacenter            = "nbg1-dc3"
  ssh_keys              = [hcloud_ssh_key.default.id]

  network {
    network_id          = hcloud_network.default_net.id
    ip                  = local.web_server_ip
  }

  depends_on            = [
    hcloud_network_subnet.default_subnet,
    hcloud_firewall.management_allow,
    hcloud_firewall.cloudflare_allow
  ]

  user_data             = data.template_file.web_cloud_init.rendered
  firewall_ids          = [
    hcloud_firewall.management_allow.id,
    hcloud_firewall.cloudflare_allow.id
  ]
}
```

**Comment by rkosegi** [comment] 2021-05-04 07:25
Can confirm that this is happening to me too. Based on my observation, it looks like allocated IP addresses are still referenced internally for some time after servers are deleted, which prevents subnet removal.

**Comment by rkosegi** [comment] 2021-05-04 09:44
Very simple way to replicate problem:
- Create server . 
- Open SSH connection to server and do eg `ping 8.8.8.8` from within SSH session
- Destroy using `terraform destroy`

SSH session will be up afterwards for some time, in my case ~5 minutes. That explains why IP address from subnet is still being referenced by server, even though it can't be seen in console or API response.

**Comment by michaelkrieg** [comment] 2021-05-05 09:46
I can also confirm that destroy does not work with this 2 provider versions:

"1.25.2"
"1.26.0"

Terraform version is v0.15.0.

**Comment by fhofherr** [comment] 2021-05-07 09:06
Hi,

unfortunately I cannot reproduce this behavior with the following configurations and the instructions posted by @michaelkrieg.

 ```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "~>1.26.0"
    }
  }
}

locals {
    web_server_ip           = "172.16.0.4"
    default_net_range       = "172.16.0.0/12"
    default_subnet_range    = "172.16.0.0/16"
}

resource "hcloud_network" "test_net" {
    name = "test-net"
    ip_range = local.default_net_range
}

resource "hcloud_network_subnet" "test_sub_net" {
    network_id = hcloud_network.test_net.id
    ip_range = local.default_subnet_range
    network_zone = "eu-central"
    type = "cloud"
}

resource "hcloud_server" "myserver" {
  name                  = "web"
  image                 = "ubuntu-20.04"
  server_type           = "cx21"
  datacenter            = "nbg1-dc3"
  ssh_keys = [ "fh@fhhc" ]

  network {
      network_id = hcloud_network.test_net.id
      ip                  = local.web_server_ip
  }

  depends_on = [
      hcloud_network.test_net,
      hcloud_network_subnet.test_sub_net
  ]
}
```

Could you please retry and if the issue still occurs post a complete minimal configuration?

**Comment by FedericoAntoniazzi** [comment] 2021-05-07 20:13
Hi @fhofherr,
I was facing the same error but I solved it thanks to your snippet.

The issue was on the myserver's dependencies because I was missing `hcloud_network.test_net`.

Before:
```hcl
depends_on = [
     hcloud_network_subnet.test_sub_net
 ]
```

After:
```hcl
depends_on = [
     hcloud_network.test_net,
     hcloud_network_subnet.test_sub_net
 ]
```

**Comment by kgusarov** [comment] 2021-05-07 20:21
Hi, @fhofherr, I will retry during next few days, however additional information I can provide so far is:

- My user data cloud-init script forms SSH connection between created servers (basically one is designated as a manager server that stores state, runs Ansible etc. - and it connects to others).
- As it was noticed by @FedericoAntoniazzi you have both net and subnet in `depends_on`. Maybe this is the issue? Can you clarify on that?

Regards,
Konstantin

**Comment by FedericoAntoniazzi** [comment] 2021-05-07 20:49
@kgusarov I think this could be a possible solution:

Terraform language is declarative and the order of the blocks doesn't matter so terraform will check only implicit and explicit dependencies when running.

In my opinion terraform decided to delete the network but to do so has to remove the subnet first. Removing the subnet imply destroying servers but the server block has an explicit dependency on the subnet. (yes, it's a loop)
By appending the network to the dependencies, you tell terraform to delete servers first and then to remove the subnet and the network.

Note that this is only my opinion and could be partially or even totally wrong


EDIT: Without the network in the dependencies, terraform raises this error: `Error: cannot remove subnet because servers are attached to it (service_error)`

EDIT: I've found another useful resource in the docs: [hetzner server network](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#network)

**Comment by FedericoAntoniazzi** [comment] 2021-05-08 12:25
**Update:** I'm trying to do more experiments on this issue and I noticed it works sometimes.
If I try to delete the subnet manually from the WebUI, I get this error:
```
Network network
Http failure response for https://api.hetzner.cloud/v1/networks/1114021/actions/delete_subnet: 422 Unprocessable Entity
```
But if I try to delete the network (manually from the WebUI) hetzner deletes the net and the subnet correctly

**Comment by michaelkrieg** [comment] 2021-05-08 12:52
With the following example this works as expected (maybe I faced a temporary issue? I deleted the network manually before in the Hetzner Cloud Web UI....)

```hcl
resource "hcloud_network" "private" {
  name     = "locust"
  ip_range = "10.20.0.0/18"
}

resource "hcloud_network_subnet" "locust" {
  ip_range     = "10.20.21.0/24"
  network_id   = hcloud_network.private.id
  network_zone = "eu-central"
  type         = "cloud"
}

resource "hcloud_server" "master" {
  image       = var.os_image
  name        = "master"
  server_type = var.server_type
  location    = var.server_locations[0]
  network {
    network_id = hcloud_network.private.id
    ip         = "10.20.21.1"
  }
  depends_on = [hcloud_network_subnet.locust]
}
variable "server_type" {
  type    = string
  default = "cx11"
}

variable "os_image" {
  type    = string
  default = "ubuntu-20.04"
}
variable "server_locations" {
  type = list(string)
  default = [
    "fsn1",
    "nbg1",
    "hel1"
  ]
}
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
  required_version = ">= 0.13"
}
```

**Comment by LKaemmerling** [comment] 2021-05-17 05:04
The problem with this issue is because terraform does not know about the dependency between a server and a subnetwork, because a subnetwork is not a root entity like a server (or a network, load balancer, or floating IP) is. The only solution is to simply `tell` terraform about this relationship like my colleague @fhofherr did above:
```
resource "hcloud_server" "myserver" {
 name                  = "web"
 image                 = "ubuntu-20.04"
 server_type           = "cx21"
 datacenter            = "nbg1-dc3"
 ssh_keys = [ "fh@fhhc" ]

 network {
     network_id = hcloud_network.test_net.id
     ip                  = local.web_server_ip
 }

 depends_on = [ # THIS CODE BLOCK
     hcloud_network.test_net, 
     hcloud_network_subnet.test_sub_net
 ]
 ```

When you specify this, Terraform can easily resolve the way how to handle the removal. Otherwise, it is luck if it works - most of the time it won't work. 

I hope this clarifies the problem. I will close the issue, if you have any questions feel free to still write here (we will read it!) and if you have another issue, feel free to open a new issue.

Thank you!
- Lukas

**Closed as completed by LKaemmerling** 2021-05-17 05:04 UTC

**Comment by kgusarov** [comment] 2021-05-17 07:41
Hi @LKaemmerling !

I can confirm, that having dependency to both net and subnet works. I guess, this should be documented :)
