### ISSUE TITLE
Adding loadbalancer target with private ip will trigger error "server is not attached to the load balancer's network"

### ISSUE THREAD

**Issue by gseidel** [hetznercloud/terraform-provider-hcloud#287] opened 2020-12-23 13:37 UTC
I use this config:

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.23.0"
    }
  }
}

variable "hcloud_token" {
    type = string
    default = "xxxxxxx"
}

provider "hcloud" {
  token = var.hcloud_token
}

resource "hcloud_network" "network-1" {
  name = "network-1"
  ip_range = "10.0.0.0/24"
}

resource "hcloud_network_subnet" "subnet-1" {
  network_id = hcloud_network.network-1.id
  type = "server"
  network_zone = "eu-central"
  ip_range   = "10.0.0.0/24"
}

resource "hcloud_load_balancer" "lb-1" {
  name = "lb-1"
  load_balancer_type = "lb11"
  location   = "fsn1"
}

resource "hcloud_load_balancer_network" "lb-1" {
  load_balancer_id = hcloud_load_balancer.lb-1.id
  network_id = hcloud_network.network-1.id
  enable_public_interface = false
}

resource "hcloud_load_balancer_service" "apiserver" {
  load_balancer_id = hcloud_load_balancer.lb-1.id
  protocol = "tcp"
  listen_port = "6443"
  destination_port  = "6443"
}

resource "hcloud_server" "node-1" {
  name = "node-1"
  image = "ubuntu-20.04"
  server_type = "cx21"
  location = "fsn1"
}

resource "hcloud_server_network" "node-1" {
  server_id = hcloud_server.node-1.id
  network_id = hcloud_network.network-1.id
}

resource "hcloud_load_balancer_target" "target-1" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-1.id
  server_id = hcloud_server.node-1.id
  use_private_ip = true
}
```

The project has no server, network or load balancer before i execute following commands (terraform v0.14.0)

```
$ terraform init
$ terraform apply
```

I receive this output with errors

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # hcloud_load_balancer.lb-1 will be created
  + resource "hcloud_load_balancer" "lb-1" {
      + id                 = (known after apply)
      + ipv4               = (known after apply)
      + ipv6               = (known after apply)
      + labels             = (known after apply)
      + load_balancer_type = "lb11"
      + location           = "fsn1"
      + name               = "lb-1"
      + network_id         = (known after apply)
      + network_ip         = (known after apply)
      + network_zone       = (known after apply)

      + algorithm {
          + type = (known after apply)
        }

      + target {
          + server_id      = (known after apply)
          + type           = (known after apply)
          + use_private_ip = (known after apply)
        }
    }

  # hcloud_load_balancer_network.lb-1 will be created
  + resource "hcloud_load_balancer_network" "lb-1" {
      + enable_public_interface = false
      + id                      = (known after apply)
      + ip                      = (known after apply)
      + load_balancer_id        = (known after apply)
      + network_id              = (known after apply)
    }

  # hcloud_load_balancer_service.apiserver will be created
  + resource "hcloud_load_balancer_service" "apiserver" {
      + destination_port = 6443
      + id               = (known after apply)
      + listen_port      = 6443
      + load_balancer_id = (known after apply)
      + protocol         = "tcp"
      + proxyprotocol    = (known after apply)

      + health_check {
          + interval = (known after apply)
          + port     = (known after apply)
          + protocol = (known after apply)
          + retries  = (known after apply)
          + timeout  = (known after apply)

          + http {
              + domain       = (known after apply)
              + path         = (known after apply)
              + response     = (known after apply)
              + status_codes = (known after apply)
              + tls          = (known after apply)
            }
        }

      + http {
          + certificates    = (known after apply)
          + cookie_lifetime = (known after apply)
          + cookie_name     = (known after apply)
          + redirect_http   = (known after apply)
          + sticky_sessions = (known after apply)
        }
    }

  # hcloud_load_balancer_target.target-1 will be created
  + resource "hcloud_load_balancer_target" "target-1" {
      + id               = (known after apply)
      + load_balancer_id = (known after apply)
      + server_id        = (known after apply)
      + type             = "server"
      + use_private_ip   = true
    }

  # hcloud_network.network-1 will be created
  + resource "hcloud_network" "network-1" {
      + id       = (known after apply)
      + ip_range = "10.0.0.0/24"
      + name     = "network-1"
    }

  # hcloud_network_subnet.subnet-1 will be created
  + resource "hcloud_network_subnet" "subnet-1" {
      + gateway      = (known after apply)
      + id           = (known after apply)
      + ip_range     = "10.0.0.0/24"
      + network_id   = (known after apply)
      + network_zone = "eu-central"
      + type         = "server"
    }

  # hcloud_server.node-1 will be created
  + resource "hcloud_server" "node-1" {
      + backup_window = (known after apply)
      + backups       = false
      + datacenter    = (known after apply)
      + id            = (known after apply)
      + image         = "ubuntu-20.04"
      + ipv4_address  = (known after apply)
      + ipv6_address  = (known after apply)
      + ipv6_network  = (known after apply)
      + keep_disk     = false
      + location      = "fsn1"
      + name          = "node-1"
      + server_type   = "cx21"
      + status        = (known after apply)
    }

  # hcloud_server_network.node-1 will be created
  + resource "hcloud_server_network" "node-1" {
      + id          = (known after apply)
      + ip          = (known after apply)
      + mac_address = (known after apply)
      + network_id  = (known after apply)
      + server_id   = (known after apply)
    }

Plan: 8 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

hcloud_network.network-1: Creating...
hcloud_server.node-1: Creating...
hcloud_load_balancer.lb-1: Creating...
hcloud_network.network-1: Creation complete after 1s [id=982108]
hcloud_network_subnet.subnet-1: Creating...
hcloud_network_subnet.subnet-1: Creation complete after 1s [id=982108-10.0.0.0/24]
hcloud_load_balancer.lb-1: Creation complete after 2s [id=168444]
hcloud_load_balancer_network.lb-1: Creating...
hcloud_load_balancer_service.apiserver: Creating...
hcloud_load_balancer_service.apiserver: Creation complete after 1s [id=168444__6443]
hcloud_load_balancer_network.lb-1: Creation complete after 3s [id=168444-982108]
hcloud_server.node-1: Still creating... [10s elapsed]
hcloud_server.node-1: Creation complete after 12s [id=9240645]
hcloud_load_balancer_target.target-1: Creating...
hcloud_server_network.node-1: Creating...
hcloud_server_network.node-1: Creation complete after 1s [id=9240645-982108]

Error: add server target: server is not attached to the load balancer's network (server_not_attached_to_network)
```

After execution I can see that the server is in the network. After applying it a second time it works. I guess the order in which the resources are added is wrong

**Comment by LKaemmerling** [comment] 2021-01-04 06:05
Hey @gseidel,

yep, this is basically a "race" condition. The problem is, that the LB will be created before the server is attached to the network. You can easily fix this within your configuration by using the terraform "configuration" "depends_on".  Have a look at https://github.com/hetznercloud/terraform-provider-hcloud/issues/170#issuecomment-651789377 to see how it works. This is something that can not be fixed within the Terraform provider, as we might guess dependencies/relationships then. 

I will close the issue, for now, feel free to write under this issue again or open up a new issue if you encounter another issue.

**Closed as completed by LKaemmerling** 2021-01-04 06:05 UTC
Labels: wontfix

**Comment by gseidel** [comment] 2021-01-04 16:13
@LKaemmerling Thanks, that help a lot
